source 'https://rubygems.org'
gem 'sinatra', '1.3.4'
gem 'rack-flash3', '1.0.1'
gem 'data_mapper', '1.2.0'
gem 'warden', '1.2.1'
gem 'dm-core'
gem  'dm-validations'
gem 'dm-timestamps'
gem 'dm-mysql-adapter'
gem 'rest_client'
gem 'dm-migrations'
gem 'bcrypt'
gem 'sinatra-formhelpers', '~> 0.4.0'